# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{is_reviewable}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonas Grimfelt"]
  s.date = %q{2009-09-18}
  s.description = %q{Rails: Make an ActiveRecord resource ratable/reviewable (rate + text), without the usual extra code-smell.}
  s.email = %q{grimen@gmail.com}
  s.extra_rdoc_files = [
    "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "generators/is_reviewable_migration/is_reviewable_migration_generator.rb",
     "generators/is_reviewable_migration/templates/migration.rb",
     "lib/is_reviewable.rb",
     "lib/is_reviewable/review.rb",
     "lib/is_reviewable/reviewable.rb",
     "lib/is_reviewable/reviewer.rb",
     "lib/is_reviewable/support.rb",
     "rails/init.rb",
     "test/is_reviewable_test.rb",
     "test/test_helper.rb"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "generators/is_reviewable_migration/is_reviewable_migration_generator.rb",
     "generators/is_reviewable_migration/templates/migration.rb",
     "lib/is_reviewable.rb",
     "lib/is_reviewable/review.rb",
     "lib/is_reviewable/reviewable.rb",
     "lib/is_reviewable/reviewer.rb",
     "lib/is_reviewable/support.rb",
     "rails/init.rb",
     "test/is_reviewable_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/grimen/is_reviewable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.3}
  s.summary = %q{Rails: Make an ActiveRecord resource ratable/reviewable (rate + text), without the usual extra code-smell.}
  s.test_files = [
    "test/is_reviewable_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
